// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjce4R5OnOW6rlYY5ik8E6k8bGeoCmnJY',
    appId: '1:878969136696:web:0278948b806016be0f68cd',
    messagingSenderId: '878969136696',
    projectId: 'parcial04-59973',
    authDomain: 'parcial04-59973.firebaseapp.com',
    storageBucket: 'parcial04-59973.appspot.com',
    measurementId: 'G-XGXRL6QNXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcnAh_LUC8m53BzI0z98GKtwEYZ2RCV4U',
    appId: '1:878969136696:android:cb838e5be44c5d520f68cd',
    messagingSenderId: '878969136696',
    projectId: 'parcial04-59973',
    storageBucket: 'parcial04-59973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7SgbUMz0E977d32e9RVY8pqchpxjMnWE',
    appId: '1:878969136696:ios:68c7f2a64439498d0f68cd',
    messagingSenderId: '878969136696',
    projectId: 'parcial04-59973',
    storageBucket: 'parcial04-59973.appspot.com',
    iosClientId: '878969136696-pk296tkcc0jgont278shrd4d3uilb285.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7SgbUMz0E977d32e9RVY8pqchpxjMnWE',
    appId: '1:878969136696:ios:68c7f2a64439498d0f68cd',
    messagingSenderId: '878969136696',
    projectId: 'parcial04-59973',
    storageBucket: 'parcial04-59973.appspot.com',
    iosClientId: '878969136696-pk296tkcc0jgont278shrd4d3uilb285.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial04',
  );
}
